name: Test, Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  Run-Test:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.18.3]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        env:
          PORT: 3000
      - run: npm install 
      - run: lastcommitsha=$GITHUB_SHA npm run build 
      - run: npm test
      - run: npm run stop
  Run-Build:
    runs-on: self-hosted

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/node-app:v1.0.$GITHUB_RUN_NUMBER .
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-app:v1.0.$GITHUB_RUN_NUMBER
        env:
          PORT: 3000      
           
      
